# Generated by Django 4.1.3 on 2024-11-02 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre Completo')),
                ('email', models.EmailField(max_length=254)),
                ('asunto', models.CharField(max_length=60, verbose_name='Asunto de su consulta')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20)),
                ('cuit', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=202)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('sexo', models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True)),
                ('localidad', models.CharField(max_length=120)),
                ('provincia', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=120, verbose_name='país')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imgPerfil', verbose_name='perfil')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='persona', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=150, verbose_name='Capacitación Tomada')),
                ('instituto_cursado', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('informacionpersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seapp.persona')),
            ],
            options={
                'verbose_name': 'información adicional',
                'verbose_name_plural': 'informaciones adicionales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idiomas', models.CharField(blank=True, max_length=50, null=True)),
                ('niv_idioma', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Competente')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('idiomapersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seapp.persona')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ExperienciaLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=150)),
                ('sec_empresa', models.PositiveSmallIntegerField(choices=[(1, 'Recursos Humanos'), (2, 'Producción'), (3, 'Finanzas / Contabilidad'), (4, 'Marketing y Ventas'), (5, 'Tecnología'), (6, 'Servicio al Cliente'), (7, 'Sistemas'), (8, 'Calidad'), (9, 'Logistica'), (10, 'Ingenieria'), (11, 'Dirección Ejecutiva'), (12, 'Otros')], verbose_name='Sector')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experienciapersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seapp.persona')),
            ],
            options={
                'verbose_name': 'experiencia laboral',
                'verbose_name_plural': 'experiencias laborales',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='EstudioRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=150)),
                ('niv_academico', models.PositiveSmallIntegerField(choices=[(1, 'Primario'), (2, 'Secundario'), (3, 'Terciario'), (4, 'Universitario')], verbose_name='Nivel Academico')),
                ('esta_estudios', models.PositiveSmallIntegerField(choices=[(1, 'Completo'), (2, 'Incompleto'), (3, 'En curso')], verbose_name='Estado de Estudios')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('estudiospersona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seapp.persona')),
            ],
            options={
                'verbose_name': 'estudio realizado',
                'verbose_name_plural': 'estudios realizados',
                'ordering': ['-id'],
            },
        ),
    ]
