# Generated by Django 4.1.3 on 2024-11-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seapp', '0002_alter_persona_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AddField(
            model_name='persona',
            name='es_persona_fisica',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='estudiospersona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seapp.persona'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True),
        ),
    ]
