# Generated by Django 4.1.3 on 2024-11-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seapp', '0003_alter_persona_options_persona_es_persona_fisica_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-id'], 'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Masculino'), (2, 'Femenino'), (3, 'Otro')], null=True),
        ),
    ]
