# Generated by Django 4.1.3 on 2024-11-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seapp', '0004_alter_persona_options_alter_persona_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomaPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=50)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='seapp.persona')),
            ],
            options={
                'verbose_name': 'idioma',
                'verbose_name_plural': 'idiomas',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='estudiospersona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudios_realizados', to='seapp.persona'),
        ),
        migrations.DeleteModel(
            name='Idiomas',
        ),
    ]
