# Generated by Django 4.1.3 on 2024-11-07 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seapp', '0005_idiomapersona_alter_estudiorealizado_estudiospersona_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={},
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='created',
        ),
        migrations.RemoveField(
            model_name='experiencialaboral',
            name='updated',
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='puesto',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='sec_empresa',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Recursos Humanos'), (2, 'Producción'), (3, 'Finanzas / Contabilidad'), (4, 'Marketing y Ventas'), (5, 'Tecnología'), (6, 'Servicio al Cliente'), (7, 'Sistemas'), (8, 'Calidad'), (9, 'Logística'), (10, 'Ingeniería'), (11, 'Dirección Ejecutiva'), (12, 'Otros')], verbose_name='Sector'),
        ),
    ]
